development:
  adapter: postgresql
  encoding: utf8
  database: pomodolist_development
  pool: 5
  username:
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: pomodolist_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: pomodolist_production
  pool: 5
  username:
  password:
